name: Go

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:

  test:
    runs-on: ${{ matrix.ubuntu_version }}
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        ubuntu_version: ['ubuntu-16.04', 'ubuntu-18.04', 'ubuntu-20.04', '>=ubuntu-20.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-Db
      run: docker-compose build
      
    - name: Create-Db
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
      
    
  build:
    needs: test
    runs-on: ${{ matrix.ubuntu_version }}
    strategy:
      matrix:
        ubuntu_version: ['ubuntu-16.04', 'ubuntu-18.04', 'ubuntu-20.04', '>=ubuntu-20.04']
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
